### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by Konishi8** [Konishi8/golf-beginner#65]
## 各種情報

サービスの概要とMVPで検証する事柄：日々のゴルフ練習を記録することができる ゴルフ練習を充実させることを目的とした 練習管理ツールです。MVPでは、記録機能に不便な点が無いか、どのようにすれば使用しやすくなるか検証してみます。

サービス名：MyGolfDiary
サービスURL：https://golf-beginner-51943945e857.herokuapp.com/
https://github.com/Konishi8/golf-beginner

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] ユーザー登録機能
- [x] ユーザープロフィール(マイページ)
- [x] ログイン機能
- [x] 練習記録作成機能
- [x] 練習記録編集機能
- [x] 練習記録削除機能 
- [x] 主軸ポイント作成機能
- [x] 主軸ポイント編集機能
- [x] 主軸ポイント削除機能

## READMEレビュー時から変更した機能

⚪︎MVPリリース時点で作らなくなった機能
パスワード変更機能 
メールアドレス変更機能 
練習メニュー定型作成
練習メニュー作成機能
練習メニュー削除機能
練習メニュー編集機能
練習記録機能　カレンダーで今までの練習量を可視化
練習何回目等でトロフィー機能

## サービスイメージがわかるようなスクリーンショット等
特になし

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by Konishi8** [comment]
ご確認頂きありがとうございました。今後とも何卒よろしくお願い申し上げます。
