### ISSUE TITLE
issueレビュー

### ISSUE THREAD

**Issue by Konishi8** [Konishi8/golf-beginner#8]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。
ゴルフの練習管理ツールです。
 １つ目はキーポイント機能です。自分でキーポイント(例：わきをしめて打つ)を作成できます。その作成したキーポイントの中から、今自分が意識しているものをお気に入りにして、それをマイページに、載せることができます。これにより、ついつい練習中に忘れがちなキーポイントを、練習前に確認する事ができます。、練習を充実させる事ができます。
 ２つ目は記録機能です。ゴルフ練習前に、その日の目標、練習メニューを決めてから練習を行い、その後コメントで振り返る事ができます。あらかじめ練習メニューや、目標を決めることにより、何となく練習する事がなくなり、練習効率が良くなります。また、練習後に振り返ることで、次の練習へと繋がります。
  3つ目は、モチベーション管理機能です。トロフィー(例：練習30日目)、練習した日が一目でわかるカレンダーがマイページにあり、それをみる事で達成感を得られます。これにより、モチベーションの低下を防ぐ事ができます。

■ProjectsのURL
https://github.com/users/Konishi8/projects/6

■MVPリリースまで

- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] トップページ
- [ ] Users作成
- [ ] 新規登録ページ
- [ ] ユーザー登録機能
- [ ] ログインページ
- [ ] ログイン機能
- [ ] マイページ
- [ ] マイプロフィールページ
- [ ] ユーザー変更ページ
- [ ] ユーザー名変更ページ
- [ ] ユーザー名変更機能
- [ ] PracticeRecords作成
- [ ] 練習記録一覧ページ
- [ ] 練習記録詳細ページ
- [ ] 練習記録作成ページ
- [ ] 練習記録編集ページ
- [ ] 練習記録作成機能
- [ ] 練習記録編集機能
- [ ] 練習記録削除機能
- [ ] KeyPoints作成
- [ ] Favorites作成
- [ ] 主軸ポイント一覧ページ
- [ ] 主軸ポイント作成ページ
- [ ] 主軸ポイント編集ページ
- [ ] 主軸ポイント作成機能
- [ ] 主軸ポイント編集機能
- [ ] 主軸ポイント削除機能
- [ ] 主軸ポイントお気に入り機能
- [ ] マイページにお気に入りが表示されるように編集

■MVP後

- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] 問い合わせフォームページ
- [ ] 問い合わせ機能
- [ ] パスワード忘れページ
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] Practices作成
- [ ] PracticeMenus作成
- [ ] 練習メニュー一覧ページ
- [ ] 練習メニュー詳細ページ
- [ ] 練習メニュー作成ページ
- [ ] 練習メニュー編集ページ
- [ ] 練習メニュー作成機能
- [ ] 練習メニュー編集機能
- [ ] 練習メニュー削除機能
- [ ] 練習記録機能カレンダー機能
- [ ] Trophies作成
- [ ] MyTrophies作成
- [ ] マイページにトロフィー一覧作成
- [ ] googleログイン機能
- [ ] lineログイン機能

■MVPレビュー依頼予定日

予定日：2024年 10月 21日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- マイページ
- ユーザー変更
- お気に入り
